version: "3"
services:
  postgis:
    image: postgis/postgis:13-3.1-alpine
    environment:
      - POSTGRES_PASSWORD=postgres
      - PGDATA=/var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    volumes:
      - "../.gitignored/dbs/pub_pgdat/.pgdata:/var/lib/postgresql/data/pgdata"
      - "../.gitignored/dbs/exchange:/tmp"
  qgs:
    image: sourcepole/qwc-qgis-server:2.18.28
    ports:
      - "8081:80"
    volumes:
      - ../.gitignored/pipe_data/qgs:/data:ro
      - ./pg_service.conf:/etc/postgresql-common/pg_service.conf:ro
    depends_on:
      - postgis
  ogc:
    image: sourcepole/qwc-ogc-service:v2.0.4
    environment:
      - JWT_SECRET_KEY=c931b344-d246-4a67-8d02-271c0e649627
      - JWT_COOKIE_CSRF_PROTECT=True
      - SERVICE_MOUNTPOINT=/ogc
      - FLASK_DEBUG=1
    volumes:
      - ../.gitignored/pipe_data/ogc:/srv/qwc_service/config/default:ro
    ports:
      - "5013:9090"
    depends_on:
      - qgs
  feat_info:
    image: sourcepole/qwc-feature-info-service:v2.0.7
    environment:
      - JWT_SECRET_KEY=c931b344-d246-4a67-8d02-271c0e649627
      - JWT_COOKIE_CSRF_PROTECT=True
      - FLASK_DEBUG=1
      - SERVICE_MOUNTPOINT=/wms_fi
    volumes:
      - ../.gitignored/pipe_data/feat_info://srv/qwc_service/config/default:ro
    ports:
      - "5015:9090"
    depends_on:
      - qgs
  legend:
    image: sourcepole/qwc-legend-service:v2.0.3
    environment:
      - JWT_SECRET_KEY=c931b344-d246-4a67-8d02-271c0e649627
      - JWT_COOKIE_CSRF_PROTECT=True
      - FLASK_DEBUG=1
      - SERVICE_MOUNTPOINT=/wms_legend
    volumes:
      - ../.gitignored/pipe_data/legend://srv/qwc_service/config/default:ro
    ports:
      - "5016:9090"
    depends_on:
      - qgs
  print:
    image: sourcepole/qwc-print-service:v2.0.2
    environment:
      - JWT_SECRET_KEY=c931b344-d246-4a67-8d02-271c0e649627
      - JWT_COOKIE_CSRF_PROTECT=True
      - FLASK_DEBUG=1
      - SERVICE_MOUNTPOINT=/print
      - OGC_SERVICE_URL=http://ogc:9090/ogc/
      - QGIS_SERVER_VERSION=2.18.19
    volumes:
      - ../.gitignored/other_data/print://srv/qwc_service/config/default:ro
    ports:
      - "5019:9090"

