version: "3"
services:
  dprod:
    image: sourcepole/sogis-dataproduct-service:v2.0.7
    environment:
      - JWT_SECRET_KEY=c931b344-d246-4a67-8d02-271c0e649627
      - JWT_COOKIE_CSRF_PROTECT=True
      - FLASK_DEBUG=1
      - SERVICE_MOUNTPOINT=/dprod
    volumes:
      - ../.gitignored/other_data/dataprod://srv/qwc_service/config/default:ro
    ports:
      - "8088:9090"

