version: "3"
services:
  dprod:
    image: sourcepole/sogis-dataproduct-service:v2.0.9
    environment:
      - JWT_SECRET_KEY=c931b344-d246-4a67-8d02-271c0e649627
      - JWT_COOKIE_CSRF_PROTECT=True
      - FLASK_DEBUG=1
      - SERVICE_MOUNTPOINT=/dprod
    volumes:
      - ../.gitignored/other_data/dataprod://srv/qwc_service/config/default:ro
    ports:
      - "8088:9090"
  document:
    image: sourcepole/qwc-document-service:v2.0.3
    environment:
      - JWT_SECRET_KEY=c931b344-d246-4a67-8d02-271c0e649627
      - JWT_COOKIE_CSRF_PROTECT=True
      - FLASK_DEBUG=1
      - SERVICE_MOUNTPOINT=/doc
    volumes:
      - ../.gitignored/other_data/report://srv/qwc_service/config/default:ro
    ports:
      - "5018:9090"
  ccc:
    image: sourcepole/sogis-ccc-config:v2.0.1
    environment:
      - JWT_SECRET_KEY=c931b344-d246-4a67-8d02-271c0e649627
      - JWT_COOKIE_CSRF_PROTECT=True
      - FLASK_DEBUG=1
      - SERVICE_MOUNTPOINT=/ccc
      - CONFIG_PATH=/srv/qwc_service/config
    volumes:
      - ../.gitignored/other_data/ccc://srv/qwc_service/config/default:ro
    ports:
      - "5021:9090"
