version: "3"
services:
  simi:
    image: postgis/postgis:13-3.1-alpine
    environment:
      - POSTGRES_PASSWORD=postgres
      - PGDATA=/var/lib/postgresql/data/pgdata
    ports:
      - "5433:5432"
    volumes:
      - "../.gitignored/dbs/simi_pgdat_test/.pgdata:/var/lib/postgresql/data/pgdata"
      - "../.gitignored/dbs/exchange:/tmp"
